
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Subtrair")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Subtrair", targetNamespace = "http://control/", className = "cliente.Subtrair")
    @ResponseWrapper(localName = "SubtrairResponse", targetNamespace = "http://control/", className = "cliente.SubtrairResponse")
    @Action(input = "http://control/Calculadora/SubtrairRequest", output = "http://control/Calculadora/SubtrairResponse")
    public int subtrair(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Soma")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Soma", targetNamespace = "http://control/", className = "cliente.Soma")
    @ResponseWrapper(localName = "SomaResponse", targetNamespace = "http://control/", className = "cliente.SomaResponse")
    @Action(input = "http://control/Calculadora/SomaRequest", output = "http://control/Calculadora/SomaResponse")
    public int soma(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Multiplicar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Multiplicar", targetNamespace = "http://control/", className = "cliente.Multiplicar")
    @ResponseWrapper(localName = "MultiplicarResponse", targetNamespace = "http://control/", className = "cliente.MultiplicarResponse")
    @Action(input = "http://control/Calculadora/MultiplicarRequest", output = "http://control/Calculadora/MultiplicarResponse")
    public int multiplicar(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns float
     */
    @WebMethod(operationName = "Dividir")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Dividir", targetNamespace = "http://control/", className = "cliente.Dividir")
    @ResponseWrapper(localName = "DividirResponse", targetNamespace = "http://control/", className = "cliente.DividirResponse")
    @Action(input = "http://control/Calculadora/DividirRequest", output = "http://control/Calculadora/DividirResponse")
    public float dividir(
        @WebParam(name = "num1", targetNamespace = "")
        float num1,
        @WebParam(name = "num2", targetNamespace = "")
        float num2);

}
